# Generated by Django 4.0.4 on 2022-05-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_walletcoinbalance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletcoinbalance',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
