# Generated by Django 4.0.4 on 2022-05-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_walletcoinbalance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletcoinbalance',
            name='usd_balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
