# Generated by Django 4.0.4 on 2022-05-15 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='is_active',
        ),
    ]
