# Generated by Django 4.0.4 on 2022-05-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_image_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AddField(
            model_name='coin',
            name='type',
            field=models.CharField(choices=[('ETHEREUM', 'Ethereum'), ('POLYGON', 'Polygon'), ('ERC_20', 'ERC-20')], default='ERC_20', max_length=20),
            preserve_default=False,
        ),
    ]
