# Generated by Django 4.0.4 on 2022-05-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_image_options_coin_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='type',
            field=models.CharField(choices=[('ETHEREUM', 'Ethereum'), ('POLYGON', 'Polygon'), ('ERC_20', 'ERC-20'), ('ATOKEN', 'AToken')], max_length=20),
        ),
    ]
