# Generated by Django 4.0.4 on 2022-05-19 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_coin_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTotalBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('usd_balance', models.FloatField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.wallet')),
            ],
            options={
                'verbose_name': 'Wallet Total Balance',
                'verbose_name_plural': 'Wallet Total Balances',
            },
        ),
    ]
