# Generated by Django 4.0.4 on 2022-05-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_wallettotalbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettotalbalance',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
